<?xml version="1.0" encoding="utf-8"?>
<!--Date format Year/Month/Day, time is 24 hour based.-->
<Acquisition>
    <Info>
        <FileVersion>2.1.2.2373</FileVersion>
        <Detector>Falcon-3</Detector>
        <AcquisitionID>TEMApps_20171201_143526</AcquisitionID>
        <Time>2017/12/01 - 14:35:28</Time>
        <ExpectedNumberOfFractions>180</ExpectedNumberOfFractions>
        <RecordedNumberOfFractions>180</RecordedNumberOfFractions>
        <Format>Signed 16 bits</Format>
        <RegionOfInterest>
            <Top>0</Top>
            <Left>0</Left>
            <Width>4096</Width>
            <Height>4096</Height>
        </RegionOfInterest>
        <Binning>1</Binning>
        <DarkCorrection>On</DarkCorrection>
        <GainCorrection>On</GainCorrection>
        <ElectronCounting>On</ElectronCounting>
        <AlignIntegratedImage>Off</AlignIntegratedImage>
    </Info>
    <Fractions>
        <Fraction>
            <Index>0</Index>
            <StartFrame>0</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:28.983</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.21928983926773</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>1</Index>
            <StartFrame>12</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:29.285</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.07715713977814</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>2</Index>
            <StartFrame>24</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:29.611</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.05529677867889</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>3</Index>
            <StartFrame>36</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:29.912</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.12790685892105</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>4</Index>
            <StartFrame>48</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:30.213</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.02658730745316</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>5</Index>
            <StartFrame>60</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:30.539</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.12848955392838</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>6</Index>
            <StartFrame>72</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:30.840</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.12886720895767</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>7</Index>
            <StartFrame>84</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:31.167</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.03547728061676</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>8</Index>
            <StartFrame>96</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:31.468</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.19194334745407</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>9</Index>
            <StartFrame>108</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:31.769</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.03985106945038</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>10</Index>
            <StartFrame>120</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:32.95</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.12760388851166</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>11</Index>
            <StartFrame>132</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:32.396</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.16483640670776</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>12</Index>
            <StartFrame>144</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:32.722</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>26.95968264341354</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>13</Index>
            <StartFrame>156</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:33.24</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.20377177000046</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>14</Index>
            <StartFrame>168</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:33.325</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.06179058551788</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>15</Index>
            <StartFrame>180</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:33.651</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.09719437360764</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>16</Index>
            <StartFrame>192</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:33.952</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.15548419952393</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>17</Index>
            <StartFrame>204</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:34.253</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.02057963609695</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>18</Index>
            <StartFrame>216</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:34.579</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.21191775798798</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>19</Index>
            <StartFrame>228</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:34.881</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.10351872444153</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>20</Index>
            <StartFrame>240</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:35.207</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.01585179567337</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>21</Index>
            <StartFrame>252</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:35.508</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.1583149433136</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>22</Index>
            <StartFrame>264</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:35.809</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.02663749456406</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>23</Index>
            <StartFrame>276</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:36.135</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.17879211902618</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>24</Index>
            <StartFrame>288</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:36.436</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.09110963344574</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>25</Index>
            <StartFrame>300</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:36.763</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.04925280809403</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>26</Index>
            <StartFrame>312</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:37.64</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.15067213773727</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>27</Index>
            <StartFrame>324</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:37.365</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.08987820148468</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>28</Index>
            <StartFrame>336</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:37.691</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.07290571928024</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>29</Index>
            <StartFrame>348</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:37.992</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.12680077552795</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>30</Index>
            <StartFrame>360</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:38.293</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>26.96071422100067</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>31</Index>
            <StartFrame>372</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:38.620</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.20432215929031</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>32</Index>
            <StartFrame>384</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:38.921</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.06410002708435</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>33</Index>
            <StartFrame>396</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:39.247</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.04025828838348</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>34</Index>
            <StartFrame>408</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:39.548</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.17175459861755</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>35</Index>
            <StartFrame>420</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:39.849</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.06282341480255</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>36</Index>
            <StartFrame>432</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:40.175</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.16680246591568</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>37</Index>
            <StartFrame>444</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:40.477</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.11064940690994</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>38</Index>
            <StartFrame>456</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:40.803</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.03480917215347</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>39</Index>
            <StartFrame>468</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:41.104</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.18466907739639</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>40</Index>
            <StartFrame>480</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:41.405</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.07712197303772</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>41</Index>
            <StartFrame>492</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:41.731</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.12558484077454</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>42</Index>
            <StartFrame>504</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:42.32</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.12618172168732</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>43</Index>
            <StartFrame>516</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:42.359</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.05004042387009</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>44</Index>
            <StartFrame>528</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:42.660</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.18767017126083</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>45</Index>
            <StartFrame>540</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:42.961</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.04997557401657</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>46</Index>
            <StartFrame>552</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:43.287</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.12832134962082</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>47</Index>
            <StartFrame>564</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:43.588</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.19256556034088</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>48</Index>
            <StartFrame>576</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:43.889</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.02808505296707</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>49</Index>
            <StartFrame>588</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:44.216</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.23203074932098</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>50</Index>
            <StartFrame>600</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:44.517</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.10585820674896</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>51</Index>
            <StartFrame>612</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:44.843</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.09439998865128</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>52</Index>
            <StartFrame>624</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:45.144</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.23120176792145</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>53</Index>
            <StartFrame>636</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:45.445</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.04166209697723</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>54</Index>
            <StartFrame>648</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:45.771</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.15317910909653</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>55</Index>
            <StartFrame>660</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:46.72</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.16880369186401</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>56</Index>
            <StartFrame>672</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:46.399</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>26.99859291315079</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>57</Index>
            <StartFrame>684</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:46.700</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.21720367670059</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>58</Index>
            <StartFrame>696</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:47.1</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.0908984541893</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>59</Index>
            <StartFrame>708</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:47.327</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.09454327821732</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>60</Index>
            <StartFrame>720</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:47.628</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.14346563816071</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>61</Index>
            <StartFrame>732</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:47.929</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.02520805597305</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>62</Index>
            <StartFrame>744</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:48.256</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.22012811899185</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>63</Index>
            <StartFrame>756</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:48.557</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.08596360683441</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>64</Index>
            <StartFrame>768</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:48.883</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.11336493492127</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>65</Index>
            <StartFrame>780</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:49.184</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.22536027431488</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>66</Index>
            <StartFrame>792</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:49.485</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.00865614414215</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>67</Index>
            <StartFrame>804</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:49.811</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.20241355895996</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>68</Index>
            <StartFrame>816</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:50.113</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.1065017580986</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>69</Index>
            <StartFrame>828</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:50.439</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.09872323274612</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>70</Index>
            <StartFrame>840</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:50.740</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.21193516254425</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>71</Index>
            <StartFrame>852</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:51.41</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.0909737944603</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>72</Index>
            <StartFrame>864</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:51.367</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.13090866804123</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>73</Index>
            <StartFrame>876</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:51.668</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.14912593364716</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>74</Index>
            <StartFrame>888</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:51.995</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.05241334438324</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>75</Index>
            <StartFrame>900</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:52.296</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.20186400413513</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>76</Index>
            <StartFrame>912</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:52.597</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.07731455564499</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>77</Index>
            <StartFrame>924</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:52.923</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.13689249753952</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>78</Index>
            <StartFrame>936</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:53.224</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.18356841802597</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>79</Index>
            <StartFrame>948</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:53.525</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.03857785463333</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>80</Index>
            <StartFrame>960</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:53.852</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.26289749145508</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>81</Index>
            <StartFrame>972</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:54.153</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.12976223230362</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>82</Index>
            <StartFrame>984</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:54.479</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.07624500989914</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>83</Index>
            <StartFrame>996</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:54.780</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.18449479341507</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>84</Index>
            <StartFrame>1008</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:55.81</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.11319404840469</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>85</Index>
            <StartFrame>1020</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:55.407</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.11803066730499</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>86</Index>
            <StartFrame>1032</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:55.709</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.16864973306656</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>87</Index>
            <StartFrame>1044</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:56.35</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.03173112869263</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>88</Index>
            <StartFrame>1056</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:56.336</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.25239336490631</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>89</Index>
            <StartFrame>1068</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:56.637</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.09239572286606</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>90</Index>
            <StartFrame>1080</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:56.963</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.12073582410812</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>91</Index>
            <StartFrame>1092</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:57.264</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.15448957681656</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>92</Index>
            <StartFrame>1104</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:57.566</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.01647764444351</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>93</Index>
            <StartFrame>1116</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:57.892</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.23907953500748</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>94</Index>
            <StartFrame>1128</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:58.193</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.11708039045334</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>95</Index>
            <StartFrame>1140</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:58.519</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.11525189876556</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>96</Index>
            <StartFrame>1152</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:58.820</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.21693217754364</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>97</Index>
            <StartFrame>1164</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:59.121</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.00716483592987</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>98</Index>
            <StartFrame>1176</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:59.448</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.19495022296906</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>99</Index>
            <StartFrame>1188</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:35:59.749</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.14591425657272</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>100</Index>
            <StartFrame>1200</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:00.75</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.09482407569885</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>101</Index>
            <StartFrame>1212</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:00.376</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.24984365701675</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>102</Index>
            <StartFrame>1224</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:00.677</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.07272827625275</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>103</Index>
            <StartFrame>1236</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:01.3</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.1686823964119</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>104</Index>
            <StartFrame>1248</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:01.305</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.15838998556137</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>105</Index>
            <StartFrame>1260</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:01.631</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.05495965480804</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>106</Index>
            <StartFrame>1272</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:01.932</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.23820155858994</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>107</Index>
            <StartFrame>1284</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:02.233</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.11587935686112</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>108</Index>
            <StartFrame>1296</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:02.559</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.12155872583389</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>109</Index>
            <StartFrame>1308</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:02.860</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.18492794036865</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>110</Index>
            <StartFrame>1320</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:03.161</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.08338016271591</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>111</Index>
            <StartFrame>1332</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:03.488</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.19442546367645</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>112</Index>
            <StartFrame>1344</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:03.789</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.12644344568253</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>113</Index>
            <StartFrame>1356</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:04.115</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.11710751056671</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>114</Index>
            <StartFrame>1368</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:04.416</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.22019600868225</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>115</Index>
            <StartFrame>1380</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:04.717</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.07497727870941</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>116</Index>
            <StartFrame>1392</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:05.44</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.17870807647705</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>117</Index>
            <StartFrame>1404</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:05.345</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.16177397966385</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>118</Index>
            <StartFrame>1416</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:05.671</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.05203753709793</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>119</Index>
            <StartFrame>1428</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:05.972</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.27210837602615</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>120</Index>
            <StartFrame>1440</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:06.273</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.11042422056198</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>121</Index>
            <StartFrame>1452</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:06.599</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.15554630756378</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>122</Index>
            <StartFrame>1464</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:06.901</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.17380148172379</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>123</Index>
            <StartFrame>1476</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:07.202</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.03800517320633</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>124</Index>
            <StartFrame>1488</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:07.528</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.26481354236603</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>125</Index>
            <StartFrame>1500</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:07.829</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.11862075328827</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>126</Index>
            <StartFrame>1512</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:08.155</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.10014075040817</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>127</Index>
            <StartFrame>1524</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:08.456</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.18728357553482</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>128</Index>
            <StartFrame>1536</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:08.757</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.1085496544838</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>129</Index>
            <StartFrame>1548</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:09.84</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.22646707296372</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>130</Index>
            <StartFrame>1560</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:09.385</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.15748327970505</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>131</Index>
            <StartFrame>1572</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:09.711</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.09615927934647</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>132</Index>
            <StartFrame>1584</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:10.12</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.26032501459122</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>133</Index>
            <StartFrame>1596</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:10.313</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.11962443590164</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>134</Index>
            <StartFrame>1608</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:10.640</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.13314878940582</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>135</Index>
            <StartFrame>1620</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:10.941</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.20311212539673</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>136</Index>
            <StartFrame>1632</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:11.267</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.04821157455444</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>137</Index>
            <StartFrame>1644</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:11.568</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.26243048906326</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>138</Index>
            <StartFrame>1656</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:11.869</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.15570366382599</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>139</Index>
            <StartFrame>1668</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:12.195</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.09714752435684</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>140</Index>
            <StartFrame>1680</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:12.496</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.20002067089081</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>141</Index>
            <StartFrame>1692</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:12.798</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.07345622777939</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>142</Index>
            <StartFrame>1704</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:13.124</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.21083211898804</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>143</Index>
            <StartFrame>1716</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:13.425</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.1071959733963</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>144</Index>
            <StartFrame>1728</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:13.751</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.12801265716553</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>145</Index>
            <StartFrame>1740</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:14.52</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.19299721717835</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>146</Index>
            <StartFrame>1752</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:14.353</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.04479712247849</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>147</Index>
            <StartFrame>1764</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:14.680</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.22503250837326</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>148</Index>
            <StartFrame>1776</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:14.981</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.14690136909485</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>149</Index>
            <StartFrame>1788</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:15.307</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.06399309635162</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>150</Index>
            <StartFrame>1800</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:15.608</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.25253170728684</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>151</Index>
            <StartFrame>1812</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:15.909</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.13510125875473</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>152</Index>
            <StartFrame>1824</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:16.235</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.14481025934219</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>153</Index>
            <StartFrame>1836</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:16.537</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.17085909843445</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>154</Index>
            <StartFrame>1848</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:16.838</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.07311904430389</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>155</Index>
            <StartFrame>1860</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:17.164</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.27380037307739</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>156</Index>
            <StartFrame>1872</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:17.465</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.1487358212471</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>157</Index>
            <StartFrame>1884</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:17.791</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.14304667711258</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>158</Index>
            <StartFrame>1896</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:18.92</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.22032999992371</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>159</Index>
            <StartFrame>1908</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:18.394</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.13241541385651</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>160</Index>
            <StartFrame>1920</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:18.720</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.23860782384872</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>161</Index>
            <StartFrame>1932</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:19.21</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.15866804122925</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>162</Index>
            <StartFrame>1944</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:19.347</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.11679297685623</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>163</Index>
            <StartFrame>1956</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:19.648</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.24257105588913</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>164</Index>
            <StartFrame>1968</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:19.949</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.13704341650009</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>165</Index>
            <StartFrame>1980</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:20.276</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.1448912024498</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>166</Index>
            <StartFrame>1992</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:20.577</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.16240900754929</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>167</Index>
            <StartFrame>2004</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:20.903</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.06463778018951</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>168</Index>
            <StartFrame>2016</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:21.204</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.24265378713608</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>169</Index>
            <StartFrame>2028</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:21.505</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.13056480884552</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>170</Index>
            <StartFrame>2040</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:21.831</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.13184612989426</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>171</Index>
            <StartFrame>2052</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:22.133</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.2326003909111</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>172</Index>
            <StartFrame>2064</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:22.434</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.09448206424713</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>173</Index>
            <StartFrame>2076</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:22.760</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.22533452510834</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>174</Index>
            <StartFrame>2088</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:23.61</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.16294801235199</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>175</Index>
            <StartFrame>2100</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:23.387</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.14822000265122</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>176</Index>
            <StartFrame>2112</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:23.688</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.22125846147537</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>177</Index>
            <StartFrame>2124</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:23.990</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.09899842739105</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>178</Index>
            <StartFrame>2136</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:24.316</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.22823518514633</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
        <Fraction>
            <Index>179</Index>
            <StartFrame>2148</StartFrame>
            <NumberOfFrames>12</NumberOfFrames>
            <SampleType>DoseFraction</SampleType>
            <Time>14:36:24.617</Time>
            <PixelValueToCameraCounts>1</PixelValueToCameraCounts>
            <ExposureTime>0.299076</ExposureTime>
            <CountsToElectrons>0.009684254</CountsToElectrons>
            <MeanPixelValue>27.18648844957352</MeanPixelValue>
            <Checksum>Valid</Checksum>
        </Fraction>
    </Fractions>
</Acquisition>
